// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace car_prob_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 17> locations_array__ =
  {" (found before start of program)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 16, column 2 to column 19)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 17, column 2 to column 14)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 21, column 2 to column 27)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 22, column 2 to column 31)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 26, column 2 to column 48)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 28, column 2 to column 29)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 29, column 2 to column 33)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 2, column 2 to column 23)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 3, column 8 to column 15)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 3, column 2 to column 37)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 5, column 27 to column 34)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 5, column 2 to column 42)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 7, column 2 to column 13)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 8, column 2 to column 13)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 9, column 2 to column 14)",
  " (in '/Users/kaylajackson/Library/CloudStorage/OneDrive-CaliforniaInstituteofTechnology/Projects/spatial-modeling/inst/stan/car_prob.stan', line 10, column 2 to column 14)"};
class car_prob_model final : public model_base_crtp<car_prob_model> {
 private:
  int count_n;
  std::vector<int> counts;
  Eigen::Matrix<double,-1,1> rates_data__;
  double bs_mu;
  double mu_mu;
  double bs_var;
  double mu_var;
  Eigen::Map<Eigen::Matrix<double,-1,1>> rates{nullptr, 0};
 public:
  ~car_prob_model() {}
  car_prob_model(stan::io::var_context& context__, unsigned int
                 random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "car_prob_model_namespace::car_prob_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 8;
      context__.validate_dims("data initialization", "count_n", "int",
        std::vector<size_t>{});
      count_n = std::numeric_limits<int>::min();
      current_statement__ = 8;
      count_n = context__.vals_i("count_n")[(1 - 1)];
      current_statement__ = 8;
      stan::math::check_greater_or_equal(function__, "count_n", count_n, 0);
      current_statement__ = 9;
      stan::math::validate_non_negative_index("counts", "count_n", count_n);
      current_statement__ = 10;
      context__.validate_dims("data initialization", "counts", "int",
        std::vector<size_t>{static_cast<size_t>(count_n)});
      counts = std::vector<int>(count_n, std::numeric_limits<int>::min());
      current_statement__ = 10;
      counts = context__.vals_i("counts");
      current_statement__ = 10;
      stan::math::check_greater_or_equal(function__, "counts", counts, 0);
      current_statement__ = 11;
      stan::math::validate_non_negative_index("rates", "count_n", count_n);
      current_statement__ = 12;
      context__.validate_dims("data initialization", "rates", "double",
        std::vector<size_t>{static_cast<size_t>(count_n)});
      rates_data__ = Eigen::Matrix<double,-1,1>::Constant(count_n,
                       std::numeric_limits<double>::quiet_NaN());
      new (&rates)
        Eigen::Map<Eigen::Matrix<double,-1,1>>(rates_data__.data(), count_n);
      {
        std::vector<local_scalar_t__> rates_flat__;
        current_statement__ = 12;
        rates_flat__ = context__.vals_r("rates");
        current_statement__ = 12;
        pos__ = 1;
        current_statement__ = 12;
        for (int sym1__ = 1; sym1__ <= count_n; ++sym1__) {
          current_statement__ = 12;
          stan::model::assign(rates, rates_flat__[(pos__ - 1)],
            "assigning variable rates", stan::model::index_uni(sym1__));
          current_statement__ = 12;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 12;
      stan::math::check_greater_or_equal(function__, "rates", rates, 0);
      current_statement__ = 12;
      stan::math::check_less_or_equal(function__, "rates", rates, 1);
      current_statement__ = 13;
      context__.validate_dims("data initialization", "bs_mu", "double",
        std::vector<size_t>{});
      bs_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 13;
      bs_mu = context__.vals_r("bs_mu")[(1 - 1)];
      current_statement__ = 14;
      context__.validate_dims("data initialization", "mu_mu", "double",
        std::vector<size_t>{});
      mu_mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 14;
      mu_mu = context__.vals_r("mu_mu")[(1 - 1)];
      current_statement__ = 15;
      context__.validate_dims("data initialization", "bs_var", "double",
        std::vector<size_t>{});
      bs_var = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 15;
      bs_var = context__.vals_r("bs_var")[(1 - 1)];
      current_statement__ = 16;
      context__.validate_dims("data initialization", "mu_var", "double",
        std::vector<size_t>{});
      mu_var = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 16;
      mu_var = context__.vals_r("mu_var")[(1 - 1)];
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1;
  }
  inline std::string model_name() const final {
    return "car_prob_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --filename-in-msg=car_prob.stan"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "car_prob_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      local_scalar_t__ log_bs = DUMMY_VAR__;
      current_statement__ = 2;
      log_bs = in__.template read<local_scalar_t__>();
      local_scalar_t__ burst_size = DUMMY_VAR__;
      current_statement__ = 4;
      burst_size = stan::math::pow(10, log_bs);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "burst_size",
        burst_size, 0);
      {
        current_statement__ = 5;
        lp_accum__.add(stan::math::neg_binomial_2_lpmf<propto__>(counts, mu,
                         stan::math::multiply(burst_size, rates)));
        current_statement__ = 6;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(mu, mu_mu, mu_var));
        current_statement__ = 7;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(log_bs, bs_mu,
                         bs_var));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "car_prob_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double mu = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      mu = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
             lp__);
      double log_bs = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      log_bs = in__.template read<local_scalar_t__>();
      double burst_size = std::numeric_limits<double>::quiet_NaN();
      out__.write(mu);
      out__.write(log_bs);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 4;
      burst_size = stan::math::pow(10, log_bs);
      current_statement__ = 3;
      stan::math::check_greater_or_equal(function__, "burst_size",
        burst_size, 0);
      if (emit_transformed_parameters__) {
        out__.write(burst_size);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, mu);
      local_scalar_t__ log_bs = DUMMY_VAR__;
      current_statement__ = 2;
      log_bs = in__.read<local_scalar_t__>();
      out__.write(log_bs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "mu", "double",
        std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "log_bs", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ mu = DUMMY_VAR__;
      current_statement__ = 1;
      mu = context__.vals_r("mu")[(1 - 1)];
      out__.write_free_lb(0, mu);
      local_scalar_t__ log_bs = DUMMY_VAR__;
      current_statement__ = 2;
      log_bs = context__.vals_r("log_bs")[(1 - 1)];
      out__.write(log_bs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"mu", "log_bs"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"burst_size"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>> temp{std::vector<size_t>{}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "log_bs");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "burst_size");
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "mu");
    param_names__.emplace_back(std::string() + "log_bs");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "burst_size");
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_bs\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"burst_size\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"log_bs\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"burst_size\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (1 + 1);
    const size_t num_transformed = emit_transformed_parameters * (1);
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = car_prob_model_namespace::car_prob_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return car_prob_model_namespace::profiles__;
}
#endif